In [22]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5,9]])  # 2D array

print(arr1)  # [1 2 3 4 5]
print(arr2)  
# [[1 2 3]
#  [4 5 6]]

[1 2 3 4 5]
[[1 2 3]
 [4 5 9]]


In [2]:
print(np.zeros((3, 3))) # 3x3 array of zeros(np.ones((2, 4))     # 2x4 array of ones
print("\n")
print(np.full((2, 2), 7)) # 2x2 array filled with 7
print("\n")
print(np.eye(4))           # 4x4 identity matrix
print("\n")
print(np.arange(1, 10, 2)) # [1, 3, 5, 7, 9] (like range)
print("\n")
print(np.linspace(0, 1, 5)) # [0. 0.25 0.5 0.75 1.] (evenly spaced)
print("\n")
print(np.ones((3, 3))) # 3x3 array of zeros(np.ones((2, 4))     # 2x4 array of ones
print("\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[7 7]
 [7 7]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[1 3 5 7 9]


[0.   0.25 0.5  0.75 1.  ]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]




In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [4]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [6]:
a=np.array([1,2,3,4])

In [7]:
a

array([1, 2, 3, 4])

In [8]:
b=np.array([[4,5,6,7],[2,3,5,5]])

In [9]:
b

array([[4, 5, 6, 7],
       [2, 3, 5, 5]])

In [10]:
b.shape

(2, 4)

In [11]:
b.size

8

In [12]:
b.ndim

2

In [13]:
type(b)

numpy.ndarray

In [17]:
c=np.arange(10,101)

In [18]:
c

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
c.shape

(91,)

In [20]:
!pip install numpy