In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print(arr1)  # [1 2 3 4 5]
print(arr2)  
# [[1 2 3]
#  [4 5 6]]

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [11]:
print(np.zeros((3, 3))) # 3x3 array of zeros(np.ones((2, 4))     # 2x4 array of ones
print("\n")
print(np.full((2, 2), 7)) # 2x2 array filled with 7
print("\n")
print(np.eye(4))           # 4x4 identity matrix
print("\n")
print(np.arange(1, 10, 2)) # [1, 3, 5, 7, 9] (like range)
print("\n")
print(np.linspace(0, 1, 5)) # [0. 0.25 0.5 0.75 1.] (evenly spaced)
print("\n")
print(np.ones((3, 3))) # 3x3 array of zeros(np.ones((2, 4))     # 2x4 array of ones
print("\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[7 7]
 [7 7]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[1 3 5 7 9]


[0.   0.25 0.5  0.75 1.  ]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]




In [12]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64
