In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # 1D array

arr1.dtype

dtype('int64')

In [2]:
arr1.astype("float64")

array([1., 2., 3., 4., 5.])

In [3]:
arr2 = np.array([1, 2, 3, 4, 5],dtype="float32")

In [4]:
arr2.dtype

dtype('float32')

In [11]:
arr2

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
b=arr2.astype("int32")

In [16]:
b

array([1, 2, 3, 4, 5], dtype=int32)

In [5]:
arr3 = np.array([1, 2, 3, 4, 5],dtype="int64")

In [7]:
arr3.dtype

dtype('int64')

In [9]:
ar=arr3.astype("int32")

In [17]:
ar.nbytes

20