In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6],[7,0,1]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [3]:
arr.sum(axis=0)

array([12,  7, 10])

In [4]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [6]:
arr[0:2,1:2]

array([[2],
       [5]])

In [7]:
print(arr.flat)

In [8]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
0
1


In [9]:
arr.ndim

2

In [10]:
arr.nbytes

72

In [11]:
arr1 = np.array([1, 2, 3, 4, 5,2,3,67,21]) 


In [12]:
print(arr1.argmax())

7


In [13]:
print(arr1.argmin())

0


In [14]:
arr1.argsort()

array([0, 1, 5, 2, 6, 3, 4, 8, 7])

In [15]:
arr4 = np.array([[1, 2, 3], [4, 5, 6],[7,0,1]])


In [16]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [17]:
arr4.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [18]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 0, 1])

In [19]:
arr.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 0, 1])

In [20]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [21]:
arr5 = np.array([[1, 2, 3], [4, 5, 6],[7,0,1]])

In [22]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [23]:
sum=arr4+arr5

In [24]:
sum

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  0,  2]])

In [25]:
mul=arr4*arr5

In [26]:
mul

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  0,  1]])

In [27]:
np.sqrt(mul)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 0., 1.]])

In [28]:
mul.sum()

np.int64(141)

In [29]:
mul.max()

np.int64(49)

In [30]:
mul.min()

np.int64(0)

In [31]:
np.where(mul>10)

(array([1, 1, 1, 2]), array([0, 1, 2, 0]))

In [32]:
np.count_nonzero(mul)

np.int64(8)

In [33]:
np.nonzero(mul)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 2]))

In [34]:
mul

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  0,  1]])

In [35]:
aa=np.empty((3,3))



In [36]:
aa

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 0., 1.]])

In [37]:
aa.shape

(3, 3)

In [38]:
f=[1.1,2.2,3.3]
arr=np.array(f)

In [39]:
arr

array([1.1, 2.2, 3.3])

In [40]:
arr.astype(int)

array([1, 2, 3])

In [41]:
g=[1,2,3,4,5,6]
a1=np.array(g)

In [42]:
a1[[1,3,5]]

array([2, 4, 6])

In [45]:
arr123 = np.array([[[1, 2, 3], [4, 5, 6],[7,0,1]],[[1, 2, 3], [4, 5, 6],[7,0,1]]])

In [52]:
arr123


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 0, 1]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 0, 1]]])

In [53]:
arr123[:1:]=0

In [54]:
arr123

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 0, 1]]])