In [2]:
l1 = [1,2,3,4]
l2 = [5,7,3,4]
list(zip(l1,l2))

[(1, 5), (2, 7), (3, 3), (4, 4)]

In [1]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)


Python list addition time: 0.17105603218078613
NumPy array addition time: 0.028857946395874023


In [2]:

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [3]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [21]:
# Python list (loop-based)
start=time.time()
list_squares = [x ** 2 for x in list1[:1000]]
end=time.time()
print(end-start)
print(f"memory:{sys.getsizeof(list_squares)*len(list_squares)} bytes")
# print(list_squares)

# NumPy (vectorized)
arr3=np.array(list(range(1000)))
start=time.time()
numpy_squares = arr3 ** 2
end=time.time()
print(end-start)
print(f"Memory :{numpy_squares.nbytes}bytes")
# print(numpy_squares)

0.0025403499603271484
memory:8856000 bytes
0.00038051605224609375
Memory :8000bytes
