In [1]:
l1 = [1,2,3,4]
l2 = [5,7,3,4]
list(zip(l1,l2))

[(1, 5), (2, 7), (3, 3), (4, 4)]

In [2]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)


Python list addition time: 0.11752104759216309
NumPy array addition time: 0.02599024772644043


In [3]:

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [4]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [5]:
# Python list (loop-based)
start=time.time()
list_squares = [x ** 2 for x in list1[:1000]]
end=time.time()
print(end-start)
print(f"memory:{sys.getsizeof(list_squares)*len(list_squares)} bytes")
# print(list_squares)

# NumPy (vectorized)
arr3=np.array(list(range(1000)))
start=time.time()
numpy_squares = arr3 ** 2
end=time.time()
print(end-start)
print(f"Memory :{numpy_squares.nbytes}bytes")
# print(numpy_squares)

0.00030803680419921875
memory:8856000 bytes
0.00042748451232910156
Memory :8000bytes


In [16]:
size=100
list11=list(range(size))
list22=list(range(size))
start=time.time()
result=[x+y for x,y in zip(list11,list22)]
end=time.time()
print(f"Memory for python list consumed:{sys.getsizeof(result)*len(result)}bytes")
print(end-start)
# print(result)
# print(list11)
arr11=np.array(list11)
arr22=np.array(list22)
start=time.time()
result=arr11+arr22
end=time.time()
print(f"Memory for numpy array is : {result.nbytes} bytes")
print(end-start)
# print(result)
# print(arr11)


Memory for python list consumed:92000bytes
0.00017070770263671875
Memory for numpy array is : 800 bytes
8.893013000488281e-05


In [19]:
list_squaress=[x**2 for x in list11]
print(list_squaress)
numpu_sq=arr11**2
print(numpu_sq)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]
[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 756